spring.application.name=starter
#spring.data.mongodb.uri=mongodb://root:root@localhost:27017/first-crud-spring-application
spring.data.mongodb.uri=mongodb://root:root@localhost:27017/first-crud-spring-application?authSource=admin
